import { AgentActionContext } from '../ToolRegistry';
import { useCoreStore } from '../../../integration/store/coreStore';
import { useUiStore } from '../../../integration/store/uiStore';
import { createRepoWithFiles, GithubError, GithubFile } from '../../integrations/github';

export interface CreateGithubRepoArgs {
  repoName: string;
  description: string;
  files: GithubFile[];
  isPrivate?: boolean;
}

/**
 * Engineering Team tool: create a real GitHub repo and push the project files.
 *
 * Reads the user's PAT from uiStore (BYOK). If no PAT is set, opens the GitHubModal
 * and aborts so the user can paste a token. On success, the repo URL is appended
 * to the agent's history and recorded in coreStore so deliver_project can mention it.
 */
export async function createGithubRepo(
  agent: AgentActionContext,
  args: CreateGithubRepoArgs
): Promise<boolean> {
  const ui = useUiStore.getState();
  const core = useCoreStore.getState();

  // Validate args
  if (!args || !Array.isArray(args.files) || args.files.length === 0) {
    core.addLogEntry({
      agentIndex: agent.data.index,
      action: 'create_github_repo failed: no files provided',
    });
    agent.appendHistory({
      role: 'tool',
      name: 'create_github_repo',
      content: 'ERROR: create_github_repo requires a non-empty `files` array. Re-run after collecting all engineer outputs.',
    });
    return true;
  }

  // Check PAT
  const pat = ui.githubConfig?.pat?.trim();
  if (!pat) {
    ui.setGitHubModalOpen(true, 'A GitHub Personal Access Token is required to create a repository. Paste one and try again.');
    core.addLogEntry({
      agentIndex: agent.data.index,
      action: 'create_github_repo blocked: no GitHub PAT configured',
    });
    agent.appendHistory({
      role: 'tool',
      name: 'create_github_repo',
      content: 'ERROR: No GitHub Personal Access Token is configured. The user has been prompted to paste one. Wait for the user to set it, then retry.',
    });
    return true;
  }

  core.addLogEntry({
    agentIndex: agent.data.index,
    action: `Creating GitHub repo "${args.repoName}" with ${args.files.length} file(s)...`,
  });

  try {
    const { repo, commit } = await createRepoWithFiles(pat, {
      name: args.repoName,
      description: args.description || 'Generated by Office-Agent Engineering Team',
      isPrivate: args.isPrivate,
      files: args.files,
    });

    core.addLogEntry({
      agentIndex: agent.data.index,
      action: `GitHub repo created: ${repo.htmlUrl} (commit ${commit.commitSha.slice(0, 7)}, ${commit.fileCount} files)`,
    });

    // Feed the URL back into the agent's history so the lead can include it in deliver_project
    agent.appendHistory({
      role: 'tool',
      name: 'create_github_repo',
      content: `SUCCESS: Repository created at ${repo.htmlUrl}\nDefault branch: ${repo.defaultBranch}\nFiles committed: ${commit.fileCount}\n\nInclude this URL as a clickable Markdown link in your final deliver_project output.`,
    });

    return true;
  } catch (e: any) {
    const isGhErr = e instanceof GithubError;
    const status = isGhErr ? e.status : 0;
    const msg = e?.message || String(e);

    core.addLogEntry({
      agentIndex: agent.data.index,
      action: `GitHub repo creation failed${status ? ` (HTTP ${status})` : ''}: ${msg}`,
    });

    // Surface auth errors to the BYOK modal so the user can fix the PAT
    if (status === 401 || status === 403) {
      ui.setGitHubModalOpen(true, msg);
    }

    agent.appendHistory({
      role: 'tool',
      name: 'create_github_repo',
      content: `ERROR: GitHub API call failed${status ? ` (HTTP ${status})` : ''}: ${msg}`,
    });

    return true;
  }
}
